language: node_js
node_js:
  - "8"

sudo: false

before_install:
  - rvm install 2.3
  - rvm use 2.3
  - gem install hiptest-publisher
  - "hiptest-publisher -c hiptest-publisher.conf --only=features,step_definitions --test-run-id=479104"
  - npm install

script:
  - node_modules/.bin/cucumber-js --format=json | node_modules/cucumber-junit/bin/cucumber-junit --features-as-suites > test-result.json

after_script:
  - hiptest-publisher -c hiptest-publisher.conf --push=test-result.json --test-run-id=479104
